services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app:ro
      - /app/node_modules
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shunyasea
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      #save as volume
      - mongo-db:/data/db
  
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app:ro
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  mongo-db: